FROM vbatts/slackware
MAINTAINER Vincent Batts <vbatts@slackware.com>
RUN TERM=linux slackpkg install php-5.4.22-x86_64-1_slack14.1 httpd-2.4.6-x86_64-1 apr-util-1.5.1-x86_64-1 sqlite-3.7.17-x86_64-1 cyrus-sasl-2.1.23-x86_64-5 apr-1.4.6-x86_64-1 

